### ISSUE TITLE
fixes for depreciated packages and other errors while running server.js

### ISSUE THREAD

**Issue by sd4-github** [sd4-github/backend_api#18]
## upgrading old npm packages
https://levelup.gitconnected.com/how-to-update-node-js-packages-db68200dfe16
````
$ npm install -g npm-check-updates ==> Install ncu (1st time)
$ ncu           ==> Show packages to be updated (Optional)
$ ncu -u        ==> Update package.json
$ npm install   ==> Update all packages
````

**Comment by sd4-github** [comment]
# source:
## upgrading old npm packages
https://levelup.gitconnected.com/how-to-update-node-js-packages-db68200dfe16
````
$ npm install -g npm-check-updates ==> Install ncu (1st time)
$ ncu           ==> Show packages to be updated (Optional)
$ ncu -u        ==> Update package.json
$ npm install   ==> Update all packages
````

## express-validator/check
![express-validator](https://user-images.githubusercontent.com/50268286/232223145-23d076dc-0014-47ed-be73-827715132f64.jpg)

````
soumikd4@soumik-inspiron3542:~/code/mycart/backend_api$ nodemon server.js
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'express-validator/check'
Require stack:
- /home/soumikd4/code/mycart/backend_api/controller/authController.js
- /home/soumikd4/code/mycart/backend_api/router/authRouter.js
- /home/soumikd4/code/mycart/backend_api/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/soumikd4/code/mycart/backend_api/controller/authController.js:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/soumikd4/code/mycart/backend_api/controller/authController.js',
    '/home/soumikd4/code/mycart/backend_api/router/authRouter.js',
    '/home/soumikd4/code/mycart/backend_api/server.js'
  ]
}
````

**Comment by sd4-github** [comment]
````
/home/soumikd4/code/mycart/backend_api/node_modules/connect-mongodb-session/index.js:88
        var e = new Error('Error connecting to db: ' + error.message);
                ^

Error: Error connecting to db: querySrv ENOTFOUND _mongodb._tcp.cluster0-bz0me.mongodb.net
    at /home/soumikd4/code/mycart/backend_api/node_modules/connect-mongodb-session/index.js:88:17
    at /home/soumikd4/code/mycart/backend_api/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:349:66

Node.js v18.16.0
````
