### ISSUE TITLE
mongodb ip whitelist

### ISSUE THREAD

**Issue by sd4-github** [sd4-github/backend_api#22]
````
soumikd4@soumik-inspiron3542:~/code/mycart/backend_api$ nodemon server.js
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
/home/soumikd4/code/mycart/backend_api/node_modules/connect-mongodb-session/index.js:88
        var e = new Error('Error connecting to db: ' + error.message);
                ^

Error: Error connecting to db: connection <monitor> to 52.0.126.221:27017 closed
    at /home/soumikd4/code/mycart/backend_api/node_modules/connect-mongodb-session/index.js:88:17
    at /home/soumikd4/code/mycart/backend_api/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:349:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                         

Node.js v18.16.0
[nodemon] app crashed - waiting for file changes before starting...
````

**Comment by sd4-github** [comment]
![image](https://user-images.githubusercontent.com/50268286/235315778-c077f7ea-e141-488d-944b-c47732ac3e0d.png)

**Comment by sd4-github** [comment]
![image](https://user-images.githubusercontent.com/50268286/235315806-cd0c796a-a039-44e8-8aa9-13d5c1cfa081.png)

![image](https://user-images.githubusercontent.com/50268286/235315832-40848459-4b53-4c53-9dc5-ce6b7a24bf16.png)
